# Default values for kitchen-wizard.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: kitchen-wizard

isLocal: false

image:
  repository: kitchen-wizard
  tag: 0.0.1
  pullPolicy: Always

resources:
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi


