isLocal: true

images:
  api:
    URI: kitchen-wizard
    tag: local
    pullPolicy: IfNotPresent
  ui:
    URI: kitchen-wizard-ui
    tag: local
    pullPolicy: IfNotPresent

apiURL: api.kitchen-wizard.local.uzcatm-skylab.com
uiURL: ui.kitchen-wizard.local.uzcatm-skylab.com
jaegerCollectorURL: collector.observability.local.uzcatm-skylab.com
dexURL: dex.dex.local.uzcatm-skylab.com

awsAccessKeyID: AKIAZHDHU5LQIDB2DGHZ

dbHostname: "acid-minimal-cluster.default.svc"
dbPort: "5432"
dbUsername: kitchenwizard
dbPassword: "passed-via-helm-command-line"


# this value is used for applications that need to communicate with services that translate to localhost. This is done so the developer can work in and out of k8s
localInterfaceIP: "value determined by make file"

