---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: store
  namespace: s3
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  virtualhost:
    fqdn: store.s3.local.uzcatm-skylab.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: store
          port: 80
---
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: kitchen-wizard-s3-bucket
  namespace: s3
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  virtualhost:
    fqdn: kitchen-wizard.store.s3.local.uzcatm-skylab.com
  routes:
    - conditions:
      - prefix: /
      services:
        - name: store
          port: 80