apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: s3
  labels:
    app: store
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: store
