apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: {{ .Values.namespace }}
  labels:
    app: ui
    chart: {{ template "kitchen-wizard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ui
    release: {{ .Release.Name }}
