apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kitchen-wizard.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "kitchen-wizard.name" . }}
    chart: {{ template "kitchen-wizard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "kitchen-wizard.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "kitchen-wizard.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /bin/api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
