apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
    chart: {{ template "kitchen-wizard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: api
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /api
          - --otp-collector-address=http://collector-collector.observability.svc:14268/api/traces
          {{ if .Values.isLocal }}
          - --dex-provider-url=https://dex.dex.local.uzcatm-skylab.com 
          - --oidc-client-id=example-app 
          - --oidc-client-secret=ZXhhbXBsZS1hcHAtc2VjcmV0
          - --oidc-redirect-url=http://api.kitchen-wizard.local.uzcatm-skylab.com
          - --postgres-db-hostname={{ .Values.dbHostname}}
          - --postgres-db-port={{ .Values.dbPort}}
          - --postgres-db-username={{ .Values.dbUsername }}
          - --postgres-db-password={ .Values.dbPassword}}
          {{ end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
            - name: grpc
              containerPort: 9443
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
