apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ template "kitchen-wizard.name" . }}
    chart: {{ template "kitchen-wizard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  virtualhost:
    fqdn: {{ .Values.apiURL }}
  routes:
    - conditions:
      - prefix: /
      services:
        - name: api
          port: 8443