{{ if .Values.isLocal }}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: acid-minimal-cluster
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    kitchenwizard:
    - login
  databases:
    kitchenwizard: kitchenwizard
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
{{ end }}