apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: {{ .Values.namespace }}
  labels:
    app: api
    chart: {{ template "kitchen-wizard.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
    - port: 9443
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: api
    release: {{ .Release.Name }}
